### ISSUE TITLE
Feature request: Add `asset-registry` migration for XCMv4 multilocations

### ISSUE THREAD

**Issue by wischli** [open-web3-stack/open-runtime-module-library#1002]
When this repository started supporting XCMv3 as part of the update to Polkadot v0.9.38 in #886, the storage version of the asset registry was bumped and a migration was added to migrate v2 locations to v3. 

I was wondering whether there are any plans to do the same for XCMv4 which was introduced in [Polkadot SDK v1.7.0](https://github.com/paritytech/polkadot-sdk/releases/tag/polkadot-v1.7.0).

**Comment by xlc** [comment]
There is no reason to migrate to v4, which is exactly the same as v3 other than version bump and rename. Best to wait for V5 and migrate to it instead.

**Comment by lemunozm** [comment]
To interact through the `asset_registry` traits (`Inspect` and `Mutate`), the API expects V4, but the `orml_asset_registry` implementation uses V3 under the hood. Do you know if all V4 locations can be internally translated to V3? Or should I expect i.e. that calling `Inspect::metadata_by_location()` can fail for some V4 Location?

**Comment by xlc** [comment]
the only thing changed is version number and otherwise 100% compatible

**Comment by lemunozm** [comment]
Thanks for the double-checking!

**Comment by wischli** [comment]
Closing due to the isometry between V3 and V4 xcm locations. Thanks for your answers @xlc!
