### ISSUE TITLE
benchmarking

### ISSUE THREAD

**Issue by xlc** [open-web3-stack/open-runtime-module-library#143]
Setup benchmarking

Something like
https://github.com/paritytech/substrate/blob/master/frame/balances/src/benchmarking.rs

- [ ] auction
- [ ] tokens

**Comment by shaopengw** [comment]
Implemented in [Acala](https://github.com/AcalaNetwork/Acala/blob/9fb9005dbfa2ba192034d7453aefbfff375137be/runtime/src/benchmarking/mod.rs#L1)
