### ISSUE TITLE
OrederedSet

### ISSUE THREAD

**Issue by xlc** [open-web3-stack/open-runtime-module-library#149]
Implement a `OrderedSet` backed by a sorted `Vec`.

This will be more efficient to handle small size set / sorted array compare to a storage map.

**Comment by burdges** [comment]
I think the [indexmap](https://github.com/bluss/indexmap) crate does this already, although it does unnecessary work to preserve the order, but we only require some deterministic order.

Actually even hashmaps become deterministic _if_ (a) you provide a deterministic `BuildHasher`, like from a blockhash, and (b) artificially restrict the size so the deterministic seed does not create a DoS attack. 

I think some custom hash or cuckoo table could embed a capacity l and a number k into some block addendum during block creation, so verification creates tables with sufficient capacity  correct size l and seeded by `block_hash ++ k`.  Your block fails validation, and results in slashing, if any bucket overflow happens, but block creation saves the final l and k for any tables used into this block addendum, so this never happens.  We'd makes block creation a probabilistic algorithm, but signatures already make that true.

**Comment by xlc** [comment]
@burdges Thanks for your input.

This will be used as an StorageValue item, so it needs fast encode/decode and relatively efficient encoding format. 

The indexmap crate seems too much for this. The number of items will needs to be relatively small anyway otherwise the decode/encode will be the performance bottleneck.

I don't think HashMap will be suitable because it need to do extra hash during decoding. Also the item can be user generated value, so an insecure hash algo could make this similar to unsorted array.

Your last approach sounds interesting, but I am not sure if the added complexity is worth the trade off. It will also need lots low level changes in Substrate so can't happen in here anyway.
