### ISSUE TITLE
MultiDataProvider

### ISSUE THREAD

**Issue by xlc** [open-web3-stack/open-runtime-module-library#245]
Make orml-oracle instantiable 

- Types
  - `trait MultiDataProvider<ProviderId, Key, Value>`
    - `fn get(source: ProviderId, key: &Key) -> Option<Value>`
  - `macro! create_midean_value_data_provider(TypeName:ident, $(Providers:ty),+)`
    - takes list of type that `impl DataProvider`
    - create a type `struct $TypeName<MinimumCount: Get<u32>, ExpiresIn: Get<Moment>, Key, Value: Ord>`
      -  `impl DataProvider` like the `DefaultCombineData` but read values from `$Providers`
- Runtime
  - `AcalaDataProvider: orml_oracle::Instance1`
  - `BandDataProvider: orml_oracle::Instance2`
  - `enum DataProviderId`
    - `AcalaDataProvier`
    - `BandDataProvider`
    - `AggergatedDataProvider`
  - `create_midean_value_data_provider(AggregatedDataProvider, AcalaDataProvider, BandDataProvider) `
  - `struct MultiDataProviderImpl`
    - `impl MultiDataProvider<DataProviderId, CurrencyId, Price>`
  - `Prices::Source = AggregatedDataProvider<Two, OneHour, CurrencyId, Price>`

**Comment by shaopengw** [comment]
Closed by #256
