### ISSUE TITLE
orml-rewards

### ISSUE THREAD

**Issue by xlc** [open-web3-stack/open-runtime-module-library#265]
- Types
  - struct PoolInfo
    - total_shares: Share
    - total_rewards: Balance
    - total_withdrawn_rewards: Balance
  - trait RewardHandler
    - type Share
    - type PoolId
    - type Balance
    - fn accumulate_reward(now: BlockNumber, callback: impl Fn(PoolId, Balance)) -> Balance
      - Check if should accumulate reward in this block
      - Call `callback` for each pool and pass how much new rewards to accumulate
    - fn payout(who: AccountId, pool: PoolId, amount: Balance)
- Trait
  - type Handler: RewardHandler
- Storage
  - Pools: map PoolId => PoolInfo
  - ShareAndWithdrawnReward: double_map (PoolId, AccountId) => (Share, Balance)
- Modules
  - add_share(who: AccountId, pool: PoolId, add_amount: Share)
  - remove_share(who: AccountId, pool: PoolId, remove_amount: Share)
  - set_share(who: AccountId, pool: PoolId, new_share: Share)
  - claim_rewards(who: AccountId, pool: PoolId)
  - on_initialize(now: BlockNumber)
    - Call Handler::accumulate_reward and update Pools

**Comment by 4meta5** [comment]
I believe `total_shares` field on `PoolInfo` struct is of type `Share`. This module outline looks great!
