### ISSUE TITLE
Add benchmarks and WeightInfo for each pallets

### ISSUE THREAD

**Issue by xlc** [open-web3-stack/open-runtime-module-library#277]
Add benchmarks for pallets without them.
Add WeightInfo for pallets without them. Example https://github.com/open-web3-stack/open-runtime-module-library/pull/261

**Comment by zjb0807** [comment]
Add WeightInfo:
- [ ] authority
- [ ] gradually-update
- [ ] oracle
- [ ] rewards

Add benchmarks:
- [ ] auction
- [ ] gradually-update
- [ ] oracle
- [ ] rewards
