### ISSUE TITLE
orml-nft should expose a trait to be consumed with other pallets

### ISSUE THREAD

**Issue by pmensik** [open-web3-stack/open-runtime-module-library#347]
The pallet is now designed in such a way that anyone who is going to use it needs to implement needs to use tight coupling. Example code of such a pallet re-use can be seen [here](https://github.com/polkadotters/SubAuction/blob/6840f51ad27ea676fe391b1fd8a200099ddff31c/pallets/nft/src/lib.rs). Is there any reason for having the Module implementation like this and not to expose pallet as a simple trait? In a similar fashion to this [PR](https://github.com/substrate-developer-hub/pallet-did/pull/12/commits/5a3d5769c12de04b42788234180894455b4afce4).
Thanks for having this dicussion, Petr

**Comment by xlc** [comment]
Tight coupling is not necessary a bad thing. Unnecessary code or leaking abstraction are something we are trying to avoid here.

As current, we don't have a use case of extra abstraction, so we don't have it.

But of course if you can provide a good use case, we could introduce it.

orml-nft is simple enough that mocking it doesn't make any sense for testing purpose and it is so simple that I don't see why we need an alternative implementation.

**Comment by danforbes** [comment]
Can you explain how exposing a trait would lead to unnecessary code leaking or abstraction? From my POV, abstraction is a good thing, and if it's designed well it will not be unnecessary. Because this pallet provides reusable capabilities that are expected to be standards-based (e.g. ERC-720), it seems _very_ reasonable to declaratively abstract it's capabilities for purposes of standardization and reuse.

**Comment by xlc** [comment]
Less code is better than more code. We don't have it is just because we don't need it (at this stage).

But I also don't have strong objections to have a trait for NFT interface so if someone PR it, I am willing to accept it.

**Comment by xlc** [comment]
Closed by https://github.com/open-web3-stack/open-runtime-module-library/pull/309
