### ISSUE TITLE
Migrate modules to use `pallet!` macro

### ISSUE THREAD

**Issue by wangjj9219** [open-web3-stack/open-runtime-module-library#354]
About how to migration: https://crates.parity.io/frame_support/attr.pallet.html#upgrade-guidelines
about how to review a migration: https://crates.parity.io/frame_support/attr.pallet.html#checking-upgrade-guidelines

Schedule:

- [x] auction
- [x] authority
- [x] currencies
- [x] gradually-update
- [x] nft
- [x] oracle
- [x] rewards
- [x] tokens
- [x] vesting

**Comment by shaopengw** [comment]
Finished.
