### ISSUE TITLE
Question: Is there an example of using the nft pallet anywhere?

### ISSUE THREAD

**Issue by MikeHuntington** [open-web3-stack/open-runtime-module-library#377]
Hello, I'm new to the orml and I was curious on how to implement the NFT pallet. I noticed there is an orml-workshop repo and I tried to duplicate what was there and apply it to using the nft module but it did not work out.

Any help would be greatly appreciated.

**Comment by xlc** [comment]
Here are two pallets using orml-nft:

https://github.com/AcalaNetwork/Acala/blob/master/modules/nft/src/lib.rs
https://github.com/usetech-llc/kusama_art_gallery/blob/master/art-gallery-pallet/src/lib.rs

**Comment by MikeHuntington** [comment]
Thank you so much for the 2nd link... it was the following syntax that was confusing me.

`nft::Module::<T>::mint()`

I'm still new to rust so I didn't realize I needed to add the <T> between Module and mint(). Again thank you for the help!
