### ISSUE TITLE
missing field `orml_nft` in initializer of `GenesisConfig`

### ISSUE THREAD

**Issue by MikeHuntington** [open-web3-stack/open-runtime-module-library#378]
After updating to orml_nft to 0.4.0 I now get the error that I'm missing orml_nft in GenesisConfig. How can this be resolved? I didn't see any documentation for this.

PS: Also ever since using the 0.4.0 crate of orml_nft, I'm unable to actually use it. Here's the error I get and I don't know if it is related to the above issue:

`pub trait Config: frame_system::Config + orml_nft::Config {
     |                                              ^^^^^^^^ use of undeclared crate or module orml_nft`

**Comment by xlc** [comment]
The error message should told you exactly what's missing. You need something like this https://github.com/AcalaNetwork/Acala/blob/6568a9d74585f786a463b03c3f0d2feef62d042f/bin/acala/service/src/chain_spec/mandala.rs#L370

**Comment by MikeHuntington** [comment]
Thanks @xlc .. The problem was that I didn't know how to actually write that block of code since I didn't see any documentation about it. But that link helped!!

Sadly the undeclared issue still happens even though I have the crate defined in the Cargo file. here's my repo that has the issue.
https://github.com/MikeHuntington/game-power-node/blob/v3/pallets/gamepower-nft/src/lib.rs

**Comment by xlc** [comment]
https://github.com/MikeHuntington/game-power-node/blob/v3/pallets/gamepower-nft/Cargo.toml#L33 it needs to be in `dependencies`

**Comment by MikeHuntington** [comment]
OMG!!! thank you again. I really appreciate your help!
