### ISSUE TITLE
XCM Fungible Asset Implementation Design

### ISSUE THREAD

**Issue by xlc** [open-web3-stack/open-runtime-module-library#384]
See https://github.com/open-web3-stack/open-runtime-module-library/discussions/385

- orml-xcm-support
  - Types
    - trait OnUnknownAssetDeposit
      - fn on_unknown_asset_deposit(id: &MultiLocation, val: u128)
    - trait AssetIdConversion
      - type Error
      - fn from_multi_asset(asset: &MultiAsset) -> Result\<Self, Error>
      - fn to_multi_asset(self: &Self) -> Result<MultiAsset, Error>
    - struct MultiCurrencyAdapter<MultCurrency, LocationConversion, AssetId: AssetIdConversion, OnUnknownAssetDeposit>
      - impl TransactAsset
        - use LocationConversion to get origin
        - ues AssetIdConversion to get CurrencyId
        - use MultiCurrency to deposit/withdraw
    - other helper types as needed
- orml-unknown-tokens
  - Notes
    - handle unknown tokens
    - allow to query balance
    - allow transfer to other chain (i.e. send money back)
  - Storages
    - map AccountId, MultiLocation => u128
  - Calls
    - transfer(origin, asset: MultiLocation, amount: u128, dest: MultiLocation)
  - Module
    - impl OnUnknownAssetDeposit
    - impl
      - fn burn(who: AccountId, asset: MultiLocation, amount: u128)
        - useful to migrate Unknown asset to known one
- orml-xtokens
  - Config
    - XcmExecutor
    - CurrencyId
    - Balance
  - Calls
    - transfer(origin, currency_id: CurrencyId, amount: Balance, dest: MultiLocation)
    - transfer_xcm(origin, asset: MultiAsset, dest: MultiLocation)

**Comment by shaunxw** [comment]
Additional implementation notes:

- In `MultiCurrencyAdapter` deposit asset impl, if the `CurrencyId` conversion failed, consider the asset as unknown asset, and deposit it via `OnUnknownAssetDeposit` trait.
- While integrating the XCM related pallets, use `orml-unknown-tokens` pallet as `OnUnknownAssetDeposit` impl in `MultiCurrencyAdapter`.
