### ISSUE TITLE
What is an alternate of OnReceived?

### ISSUE THREAD

**Issue by ayushmishra2005** [open-web3-stack/open-runtime-module-library#390]
In 0.3.2, there was OnReceived  function https://github.com/open-web3-stack/open-runtime-module-library/blob/0.3.2/traits/src/currency.rs#L322, But it is missing in 0.4.0.

I also didn't find the release document. What is the alternate of this in new version?

**Comment by xlc** [comment]
https://github.com/open-web3-stack/open-runtime-module-library/blob/92db458616cae0da1cc55fa90962e2ed16d45279/traits/src/lib.rs#L67-L70

`Happened` is a more generic version of it.

This is an example usage https://github.com/AcalaNetwork/Acala/blob/ac5944918db5b14f0412bf3a5fa45f30814aa7ff/modules/loans/src/lib.rs#L69
