### ISSUE TITLE
Instantiable tokens pallet

### ISSUE THREAD

**Issue by olanod** [open-web3-stack/open-runtime-module-library#391]
Valiu has a use case for having different "groups" of tokens. With a single instance of the tokens pallet if another pallet that depends on a `MultiCurrency` wants to restrict the kind of token it accepts then a separate configuration to whitelist the subset of allowed currency ids might be needed. I can rely on the type system alone if I know the `MultiCurrency` has the right set of currency ids.

**Comment by xlc** [comment]
RP are welcome!

Also one way to achieve your goal without multiple tokens pallet is do something like this:

```
enum CryptoCurrencyId {
  BTC,
  ETH,
}

enum FiatCurrencyId {
  USD,
  EUR,
}

enum CurrencyId {
  Crypto(CryptoCurrencyId),
  Fiat(FiatCurrencyId),
}
```

So one tokens pallet can handle two kinds of currencies.

And you can have custom adaptors to handle currency id conversion

```
struct CryptoCurrencies;

impl MultiCurrency for CryptoCurrencies {
  type CurrencyId = CryptoCurrencyId;

  fn total_issuance(currency_id: CryptoCurrencyId) -> Self::Balance
     Tokens::total_issuance(CurrencyId::Crypto(currency_id))
  }
}

```

And you can abstract it to have some `CurrencyIdConverter: Fn(A) -> B` to make it generalized
