### ISSUE TITLE
Implement multicurrency trait for xtokens 

### ISSUE THREAD

**Issue by olanod** [open-web3-stack/open-runtime-module-library#398]
More of a question to understand better how xtokens will work. Not sure if its a goal of xtokens to be a drop-in replacement for tokens pallet, if that's the case I assume it should implement some of the traits that tokens pallet also implements like `MultiCurrency`?

**Comment by xlc** [comment]
You can just check how Acala / Plasm / HydraDX is using xtokens.

It only handles the XCM part, and still uses orml-tokens to handle MultiCurrency

**Comment by shaunxw** [comment]
@olanod Just to clarify, xtokens is not a replacement for tokens pallet, the asset withdraw/deposit/transfer is still handled by tokens pallet.

**Comment by olanod** [comment]
Thanks, yeah that's what I realized when checking the code, I guess it was the name of the pallet that made me assume it was a cross chain version of the tokens pallet even if it meant just wrapping the existing pallet. Just to confirm, keeping both separate is by design and xtokens scope will remain just being a convenience higher level abstraction for sending tokens via XCM, correct?

**Comment by shaunxw** [comment]
Yes you're right. What xtokens does is basically translate dispatchable calls like `transfer_to_relay_chain` into an XCM message and then send it.

**Comment by xlc** [comment]
Close as answered
