### ISSUE TITLE
Remove clear_on_drop once Cargo fixes the feature pollution problem

### ISSUE THREAD

**Issue by xlc** [open-web3-stack/open-runtime-module-library#41]
`clear_on_drop` is needed to workaround Cargo feature pollution issue. They should be removed once Cargo fixes this problem.

https://github.com/laminar-protocol/open-runtime-module-library/blob/26513636628caac97526b199e7cc26340ed7f6e8/auction/Cargo.toml#L23

Related: https://github.com/paritytech/substrate/issues/4179

**Comment by shaunxw** [comment]
`clear_on_drop` has been removed.
