### ISSUE TITLE
orml-claims

### ISSUE THREAD

**Issue by xlc** [open-web3-stack/open-runtime-module-library#425]
- orml-claims
  - Types
    - trait OnClaim<AccountId, P>
      - fn on_claim(who: &AccountId, payload: P) -> DispatchError
        - This should fail on duplicated claim
  - Config
    - type OnClaim: OnClaim
    - type UpdateTrieRootOrigin: EnsureOrigin
  - Storage
    - TrieRoot: Hash
  - Calls
    - fn set_trie_root(origin, new_root: Hash)
      - ensure UpdateTrieRootOrigin
      - update TrieRoot
    - fn claim(origin, to: AccountId, payload: Payload, proof: Vec\<u8>)
      - ensure signed
      - verify proof
      - `OnClaim::on_claim(to, payload)`
  - Note
    - This is intented to be used to store crowdloan rewards
    - Proxy / Multisig accounts can send Transact XCM on relaychain to invoke claim
    - Need to make this a unsigned transaction so people can claim it without paying fee

**Comment by lucasvo** [comment]
Sharing a bit more on what Centrifuge has been working on here: https://centrifuge.hackmd.io/NPmnf3a2R3SAN75nA-QSRw

**Comment by lucasvo** [comment]
Is the intention that the trie root matches the format of the relaychain crowdloan child trie?

**Comment by xlc** [comment]
> Is the intention that the trie root matches the format of the relaychain crowdloan child trie?

Yes. To keep it simple. It should be possible to abstract it away but unless someone request it, I want to avoid unnecessary features to keep thing simple.

**Comment by lucasvo** [comment]
I would suggest we call it `orml-crowdloan-claims` to make it a bit more specific :)

**Comment by xlc** [comment]
This is designed to be used with crowdloan but I think it can also be repurposed for other use cases such as airdrops.

**Comment by lucasvo** [comment]
@xlc have you started your own implementation of this? Our progress is here: https://github.com/centrifuge/centrifuge-chain/pull/342

**Comment by xlc** [comment]
We have not started working on this. Depends on how much time we have before crowdloan, we may just distribute rewards via batch call.

**Comment by xlc** [comment]
We won't be working on this.
