### ISSUE TITLE
how to display PoolInfo in polkadot.js? (orml-rewards-0.4.0)

### ISSUE THREAD

**Issue by ziwenxie** [open-web3-stack/open-runtime-module-library#430]
Following is the substrate debug log:
```rust
debug::info!(target: "incentives debug 2:", "pool_id:{:?}, pool_info: {:?}", pool_id, pool_info);

output => `debug 2:: pool_id:1, pool_info: PoolInfo { total_shares: 20100000000000000000, total_rewards: 12279504950495, total_withdrawn_rewards: 12049504950495 } `
```

The json configuration is as follows:
```json
{
  "Balance": "u128",
  "BalanceOf": "Balance",
  "PoolInfo": {
    "total_shares": "Balance",
    "total_rewards": "Balance",
    "total_withdrawn_rewards": "Balance"
  },
  "PoolInfoOf": "PoolInfo"
}
```

Following is the screenshot in https://polkadot.js.org/apps:

![image](https://user-images.githubusercontent.com/24546717/112998641-d1778d00-91a0-11eb-833d-981576e23cd8.png)

Inconsistent data on both sides？

[poolinfo-source-code](https://github.com/open-web3-stack/open-runtime-module-library/blob/0.4.0/rewards/src/lib.rs#L22)

**Comment by xlc** [comment]
You may have defined the type differently. Not much I can help without seeing your code.

**Comment by ziwenxie** [comment]
Fixed by using `Compact<u128>`:

```json
{
  "Balance": "u128",
  "BalanceOf": "Balance",
  "PoolInfo": {
    "total_shares": "Compact<u128>",
    "total_rewards": "Compact<u128>",
    "total_withdrawn_rewards": "Compact<u128>"
  },
  "PoolInfoOf": "PoolInfo"
}
```

 Is there a way to automatically generate a `types.json` configuration file for polkadot.js?

**Comment by xlc** [comment]
No. You can see more discussion at https://github.com/paritytech/substrate/discussions/8370
