### ISSUE TITLE
Why tokens.transfer is asking for transaction fee with ORML 0.4.0 and Substrate 3.0.0

### ISSUE THREAD

**Issue by ashi20192020** [open-web3-stack/open-runtime-module-library#433]
I am using ORML tokens pallet for one of my applications. Earlier I was using **ORML 0.3.2** and **Substrate 2.0**. Below is Runtime configuration of `pallet_transaction_payment` and `orml:token`

```
parameter_types! {
	pub const TransactionByteFee: Balance = 0;
}

impl pallet_transaction_payment::Trait for Runtime {
	type Currency = Balances;
	type OnTransactionPayment = ();
	type TransactionByteFee = TransactionByteFee;
	type WeightToFee = IdentityFee<Balance>;
	type FeeMultiplierUpdate = ();	
}

impl tokens::Trait for Runtime {
	type Event = Event;
        type Balance = Balance;
	type Amount = i64;
	type CurrencyId = i64;
        type OnReceived = ();
        type WeightInfo = ();
}
```
With the above configuration, I was able to transfer without any transaction fee. Recently I have updated my application with  ORML 0.4.0 and Substrate 3.0.0. Below is Runtime configuration:

```
parameter_types! {
	pub const TransactionByteFee: Balance = 0;
}

impl pallet_transaction_payment::Config for Runtime {
	type OnChargeTransaction = CurrencyAdapter<Balances, ()>;
	type TransactionByteFee = TransactionByteFee;
	type WeightToFee = IdentityFee<Balance>;
	type FeeMultiplierUpdate = ();
}

impl tokens::Trait for Runtime {
	type Event = Event;
        type Balance = Balance;
	type Amount = i64;
	type CurrencyId = i64;
        type OnReceived = ();
        type WeightInfo = ();
}
```
As you can see, there is no change in the `token` configuration but in `pallet_transaction_payment`, `Currency` got replaced by `OnChargeTransaction`. As a result, it started asking for transaction fee. 

![image](https://user-images.githubusercontent.com/81686485/113476142-324fdf80-9497-11eb-8c1d-e56e801cb56e.png)

**Comment by ashi20192020** [comment]
Can someone please help me to understand and fix this issue?

**Comment by ashi20192020** [comment]
Adding `Pays::No` in weights solved the issue. Is that the only solution?

**Comment by ayushmishra2005** [comment]
Adding `Pays::No` in weights will solve the issue. I am not sure whether this is the only solution.

**Comment by wangjj9219** [comment]
Because the default weight is not zero：https://github.com/open-web3-stack/open-runtime-module-library/blob/db10cfda77388524b6b30faa7300b165c740e6d4/tokens/src/default_weight.rs#L9-L20

you can overwrite the weight info by defining `type WeightInfo = `

**Comment by ashi20192020** [comment]
> Because the default weight is not zero：
> 
> https://github.com/open-web3-stack/open-runtime-module-library/blob/db10cfda77388524b6b30faa7300b165c740e6d4/tokens/src/default_weight.rs#L9-L20
> 
> you can overwrite the weight info by defining `type WeightInfo = `

@wangjj9219 How it was working earlier then? I didn't make any chain in weight file. Earlier it was charging 0 transaction fee as per this configuration.

**Comment by xlc** [comment]
This has nothing to do with orml. You just need to config your runtime to not charge fee.

For example `type WeightToFee = IdentityFee<Balance>;` can be changed to something returns zero.
