### ISSUE TITLE
implementation question 

### ISSUE THREAD

**Issue by OutofThematrix** [open-web3-stack/open-runtime-module-library#462]
I am trying to implement the auction pallet. I am getting some errors to test and work with it. If you could help me out with the implementation that would be great. Here is what i have. I am getting some errors using this config. Im not sure how to implement the balances etc. 

impl orml_auction::config for Runtime {
	type Event = Event;
	type Balance = Balances;
	type Handler = AuctionHandler;
	type WeightInfo = WeightInfo;
	type AuctionId = AuctionId;
}

**Comment by xlc** [comment]
You can check the tests as an example https://github.com/open-web3-stack/open-runtime-module-library/blob/master/auction/src/mock.rs
