### ISSUE TITLE
Using `orml_tokens` and `pallet-balances` together in runtime, how to decoding the different `AccountData` struct in polkadot-js api?

### ISSUE THREAD

**Issue by jimmychu0807** [open-web3-stack/open-runtime-module-library#499]
@xlc I am following the orml-workshop integrating `orml_tokens` and `orml_currencies` in the node-template runtime, together with Substrate existing `pallet_balances`. 

But following current orml `master` branch with upstream Substrate `polkadot-v0.9.1` branch, the `AccountData` struct is different. orml_tokens has:

```rust
pub struct AccountData<Balance> {
	pub free: Balance,
	pub reserved: Balance,
	pub frozen: Balance,
}
```

while Substrate has:

```rust
pub struct AccountData<Balance> {
	pub free: Balance,
	pub reserved: Balance,
	pub misc_frozen: Balance,
	pub fee_frozen: Balance,
}
```

One `AccountInfo` type in polkadot-js API cannot satisfied both at the same time. How do you see the best way to resolve this? 

- Extending `orml_tokens` AccountData to use `misc_frozen` and `fee_frozen`?
- Or dropping the `pallet_balances` in runtime (is it possible to drop `pallet_balances` without major changes to other parts in runtime?)

**Comment by xlc** [comment]
https://github.com/AcalaNetwork/acala.js/blob/43d1d3f749317d085b7ad204126b6014cc7f9143/packages/type-definitions/src/json/typesBundle.json#L2331-L2335

You can set account alias for polkadot.js

There are many types shares same name in Substrate like `Proposal`

Ask Jaco or make issue on polkadot.js should get you better answer.

**Comment by jimmychu0807** [comment]
I see. Thanks for the reply
