### ISSUE TITLE
if dest_weight is not enough then xcm upward transfer fails with Incomplete::Barrier message

### ISSUE THREAD

**Issue by GopherJ** [open-web3-stack/open-runtime-module-library#535]
This happened when I use 100000 as weight, if I use 1000000 it succeeds without any issue

tokens are withdrawn but didn't arrive at dest account

**Comment by GopherJ** [comment]
This is actually dangerous and needs maybe to be documented somewhere

**Comment by xlc** [comment]
This is not something we can fix here. Please report to Polkadot repo.

Only thing we can do is add some warning but no user is going to see it. We do need to add more docs for developers.

**Comment by GopherJ** [comment]
@xlc sure I'll report it to polkadot, but maybe we need also some more docs for developers, thanks for your reply
