### ISSUE TITLE
XCM: make xtokens `do_` functions pub

### ISSUE THREAD

**Issue by mattsse** [open-web3-stack/open-runtime-module-library#537]
executing XCM transfers are currently limited to dispatchable calls.
can the private `do_` be made `pub` so xtokens transfers can be executed directly from other pallets?

**Comment by xlc** [comment]
I am happy to accept a PR that:

- define a `trait XcmTransfer` in orml-triats includes all the necessary methods
- have orml-xtokens implements `XcmTransfer` trait
