### ISSUE TITLE
What is the use of `BlockNumberProvider` in Vesting module?

### ISSUE THREAD

**Issue by ayushmishra2005** [open-web3-stack/open-runtime-module-library#563]
What is the use of `BlockNumberProvider` in Vesting module?

https://github.com/open-web3-stack/open-runtime-module-library/blob/master/vesting/src/lib.rs#L149

I found that Acala is using `RelaychainBlockNumberProvider` but I am not able to understand this.

https://github.com/AcalaNetwork/Acala/blob/master/runtime/common/src/lib.rs#L171

**Comment by xlc** [comment]
Allow people to choose current blockchain number or relaychain number for vesting.
