### ISSUE TITLE
Fatal: not a git repository (or any of the parent directories): .git

### ISSUE THREAD

**Issue by sagaratalatti** [open-web3-stack/open-runtime-module-library#577]
I am running the command git submodule sync

Here's the default .submodules file

```
[submodule "orml"]
	path = orml
	url = https://github.com/open-web3-stack/open-runtime-module-library.git
```
I running this command through Powershell on Windows 10

**Comment by xlc** [comment]
That's not enough information and we don't use Windows so can't help much about this. Do you have .git folder?
The error is unlikely have anything to do with this repo anyway so will close.

**Comment by sagaratalatti** [comment]
> That's not enough information and we don't use Windows so can't help much about this. Do you have .git folder?
> The error is unlikely have anything to do with this repo anyway so will close.

Would like to ask if the submodule orml directory has been changed? I am building REEFCHAIN project.
