### ISSUE TITLE
 Implement `nonfungibles::*` for orml-nft

### ISSUE THREAD

**Issue by kinosang** [open-web3-stack/open-runtime-module-library#654]
Do you accept a contribute to implement `nonfungibles::*` traits introduced in paritytech/substrate#8993 for orml-nft?

**Comment by xlc** [comment]
Yes that will be helpful.

**Comment by kinosang** [comment]
Unfortunately, `ClassData` and `TokenData` are not supported by `nonfungibles` traits.

**Comment by xlc** [comment]
What do you mean? It doesn't prevent us to implement `nonfungibles` traits?
