### ISSUE TITLE
Be able to specify the fee aside the amount to be transferred in Xtokens

### ISSUE THREAD

**Issue by girazoki** [open-web3-stack/open-runtime-module-library#655]
This is a usecase we encountered in Moonbeam, where we need to specify the fee (the amount to be provided in BuyExecution) as a separate argument to the amount being transferred, with the goal of better controlling the amount received in the destination side. We are in the process of adding this to Xtokens in our own fork, would you be interested on having such feature too? I could do a  PR with my changes if you are interested

**Comment by girazoki** [comment]
Just FYI, I am making this changes as an additional functionality (by adding two new extrinsics), I am not changing any of the existing functionality in Xtokens

**Comment by xlc** [comment]
Happy to accept PR as long as it is transaction version compatible.

**Comment by girazoki** [comment]
This is a first drafter, let me know if this is something you would like to add https://github.com/open-web3-stack/open-runtime-module-library/pull/658
