### ISSUE TITLE
support transfering multiple assets(now only one)  in orml-xtokens

### ISSUE THREAD

**Issue by yrong** [open-web3-stack/open-runtime-module-library#663]
related issues and prs:

https://github.com/paritytech/cumulus/issues/827
https://github.com/paritytech/cumulus/pull/806
https://github.com/paritytech/polkadot/pull/4470

wrap xcm as following when send statemine asset back:
https://github.com/bifrost-finance/bifrost/blob/c7eb1bef7abfdeb6562aeda29ab76805308b77f5/pallets/salp/src/lib.rs?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L1012-L1031

**Comment by girazoki** [comment]
Just wanted to cross-post some a thought I had in https://github.com/bifrost-finance/bifrost/pull/420 here too

```
HI! Just curious about the same problem (sending statemine assets back to statemine) and I am wondering a few things about this implementation:

In transfer_statemine_assets, this PR is doing initateReserveWithdraw of both the statemine asset and the relay token (to be able to pay in for fees in statemine). This therefore implies that the sovereign account in Statemine holds both tokens (to be able to withdraw them?).

If the above is true, wouldnt we have two sovereign accounts (the one in statemint, and the one in the relay) holding the relay token? And since both match to the same token in the bifrost parachain, wouldnt this imply that we could face the situation where a user transfers to the relay chain more tokens than what the sovereign account in the relay holds?
```

**Comment by xlc** [comment]
The reserve chain of KSM is Kusama, not Statemine, so we will simply reject direct KSM transfer from Statemine.

**Comment by girazoki** [comment]
How are you going to handle sending statrmine assets back to statemine then? given that statemine fees can only be paid in KSM, I am guessing the sovereign account in statemine will need to have KSM somehow.

**Comment by xlc** [comment]
Yeah XCM basically offers no solution on manage fees on sovereign account (you can't really track how much fee is charged). So the simple solution is just topup the sovereign account on Statemine somehow. It can be done manually, or should be possible to do a reserve transfer of KSM to Kusama and teleport it to Statemine parachain sovereign account.

**Comment by yrong** [comment]
resolved in https://github.com/open-web3-stack/open-runtime-module-library/pull/658
