### ISSUE TITLE
NamedReservableCurrency equivalent for MultiReservableCurrency

### ISSUE THREAD

**Issue by olanod** [open-web3-stack/open-runtime-module-library#668]
Just as with [`NamedReservableCurrency`](https://github.com/paritytech/substrate/blob/master/frame/support/src/traits/tokens/currency/reservable.rs#L84), it is quite useful if the same can exist for the `MultiCurrency` family. Pallets can reserve under a namespace without fear of interfering with other modules.

**Comment by xlc** [comment]
I was hoping the NamedHolds fungible traits could be implemented and we can switch to it instead. But looks like that's not going to happen anytime soon.

PR are welcome.
