### ISSUE TITLE
Expose ExistentialDeposits as constant

### ISSUE THREAD

**Issue by gregdhill** [open-web3-stack/open-runtime-module-library#682]
Downstream systems need an easy way to query these, not sure if this is currently possible since the `Config` type parameter is not a constant so won't be included in the pallet metadata.

**Comment by xlc** [comment]
The main issue is that it is not really a constant for Acala https://github.com/AcalaNetwork/Acala/blob/35078ea2b2d0e3a3937a075c54d94c77faea2f36/runtime/acala/src/lib.rs#L770-L793

Even if they are constant, I am not sure what's the best way to expose a Key Value mapping via metadata

**Comment by gregdhill** [comment]
Perhaps we can expose some RPC call for this instead? Would definitely be useful for wallets and other integrations.

**Comment by xlc** [comment]
Yep that will be a good solution.
