### ISSUE TITLE
Add MaxEncodedLen bound to MultiCurrency

### ISSUE THREAD

**Issue by stanly-johnson** [open-web3-stack/open-runtime-module-library#686]
Is it possible to add the `MaxEncodedLen` bound to `Balance` and `CurrencyId` of `MultiCurrency` and related traits similar to [substrate](https://github.com/paritytech/substrate/blob/ded44948e2d5a398abcb4e342b0513cb690961bb/frame/support/src/traits/tokens/currency.rs#L37), makes it possible to use
`MultiCurrency<<T as frame_system::Config>::AccountId>>::Balance` as a storage item.

I can make the PR if no objections

**Comment by xlc** [comment]
PRs are welcome
