### ISSUE TITLE
Failed execute transfer message with AssetNotFound

### ISSUE THREAD

**Issue by 99Kies** [open-web3-stack/open-runtime-module-library#701]
Now I have two parachains A and B, They all added the XTokens module.
I want to send some a_token to an account on chain B. So I used `xtokens.transfer`. 
However, the execution failed. Here is some configuration information and error logs.

![image](https://user-images.githubusercontent.com/45918704/155089744-89266a2d-2425-4c0d-9421-d1cb8c5e527f.png)

extrinsic & event message:
![01386e6899cb4c449e4ff50323cf508](https://user-images.githubusercontent.com/45918704/155089710-2c0ad224-b41a-4247-8c0e-7675d0ff9083.png)

xcm log info:
![1645517524](https://user-images.githubusercontent.com/45918704/155089896-ccb13f18-3f51-4ea4-b5ae-888256769fd5.png)

Here are my configuration details: https://github.com/99Kies/Cross-Chain/blob/main/runtime/src/lib.rs#L640-L730

**Comment by zqhxuyuan** [comment]
AssetNotFound is raised by un-match asset:

https://github.com/paritytech/polkadot/blob/4248524da7b90e17baefde5360cc7860a1e3292b/xcm/xcm-builder/src/currency_adapter.rs#L162-L166

you should debug and found why `Matcher` is not matched.

**Comment by 99Kies** [comment]
This reason is too basic.😢

> AssetNotFound 由不匹配的资产引发：
> 
> https://github.com/paritytech/polkadot/blob/4248524da7b90e17baefde5360cc7860a1e3292b/xcm/xcm-builder/src/currency_adapter.rs#L162-L166
> 
> 您应该调试并找到`Matcher`不匹配的原因。

**Comment by 99Kies** [comment]
I configured it according to `xtokens/src/mock/mod.rs`. -> https://github.com/open-web3-stack/open-runtime-module-library/blob/master/xtokens/src/mock/mod.rs#L21-L89
Could you please help me check my `orml-xtokens` configuration? -> https://github.com/99Kies/Cross-Chain/blob/main/runtime/src/lib.rs#L640-L730

**Comment by xlc** [comment]
You really need to write some tests and just debug it. This is not the right please for XCM support.
