### ISSUE TITLE
Questions about configuring CurrencyIdConvert

### ISSUE THREAD

**Issue by 99Kies** [open-web3-stack/open-runtime-module-library#709]
平行链A向平行链B转平行链A的原生代币，平行链A成功执行了交易，但是在平行链B却报了`AssetIdConversionFailed`的错误信息。
这是我在平行链A下执行交易的参数。
![image](https://user-images.githubusercontent.com/45918704/156429553-2980e9e4-2854-4cb7-9bfb-9406fdfcc5e3.png)
这是平行链B的日志信息
 ![image](https://user-images.githubusercontent.com/45918704/156392407-7c0571f7-9057-4f3d-b375-ece7260e3576.png)
这是我在平行链B的CurrencyIdConvert的配置。
```rust
impl Convert<MultiLocation, Option<CurrencyId>> for CurrencyIdConvert {
	fn convert(l: MultiLocation) -> Option<CurrencyId> {
        let ff: Vec<u8> = "FF".into();
        let dora: Vec<u8> = "DORA".into();
		if l == MultiLocation::parent() {
			return Some(CurrencyId::ROC);
		}

		match l {
			MultiLocation { parents, interior } if parents == 1 => match interior {
				X2(Parachain(1000), GeneralKey(k)) if k == ff => Some(CurrencyId::FF),
				X2(Parachain(2000), GeneralKey(k)) if k == dora => Some(CurrencyId::DORA),
				_ => None,
			},
			MultiLocation { parents, interior } if parents == 0 => match interior {
				X1(GeneralKey(k)) if k == ff => Some(CurrencyId::FF),
				X1(GeneralKey(k)) if k == dora => Some(CurrencyId::DORA),
				_ => None,
			},
			_ => None,
		}
	}
}
```
这是平行链B下的日志，我根据日志里的参数结合我的CurrencyIdConvert推断，不是可以获取到CurrencyId::FF的吗？

> TRACE tokio-runtime-worker xcm::fungibles_adapter: [Parachain] deposit_asset what: MultiAsset { id: Concrete(**`MultiLocation { parents: 1, interior: X2(Parachain(1000), GeneralKey([70, 70])) }`**), fun: Fungible(50000000000000) }, who: MultiLocation { parents: 0, interior: X1(AccountId32 { network: Any, id: [212, 53, 147, 199, 21, 253, 211, 28, 97, 20, 26, 189, 4, 169, 159, 214, 130, 44, 133, 88, 133, 76, 205, 227, 154, 86, 132, 231, 165, 109, 162, 125] }) }

**Comment by 99Kies** [comment]
"FF".into() 的值就是 [70, 70]

**Comment by zqhxuyuan** [comment]
you need to find where `AssetIdConversionFailed` is. also maybe your interior `Parachain(1000)` is wrong.

**Comment by 99Kies** [comment]
@zqhxuyuan parachainA is 1000, parachainB is 2000.

**Comment by 99Kies** [comment]
<img width="1503" alt="image" src="https://user-images.githubusercontent.com/45918704/156498886-0819d9a4-ce3c-4101-895d-090dd107e8a0.png">

**Comment by 99Kies** [comment]
> you need to find where `AssetIdConversionFailed` is. also maybe your interior `Parachain(1000)` is wrong.

I can't make a log ini CurrencyIdConvert.

**Comment by 99Kies** [comment]
i fixed it
