### ISSUE TITLE
[Relaychain] Execution errored at 2: MaxWeightInvalid

### ISSUE THREAD

**Issue by 99Kies** [open-web3-stack/open-runtime-module-library#715]
this relaychain-encoded hash:
<img width="1507" alt="image" src="https://user-images.githubusercontent.com/45918704/158749720-18f939e9-0911-46fe-94ce-8e9d2e968ce9.png">

ormlxcm on my parachain:
<img width="1511" alt="image" src="https://user-images.githubusercontent.com/45918704/158749415-1193d9d5-1d7c-48d4-b966-a83f5cbac1c0.png">
<img width="1502" alt="image" src="https://user-images.githubusercontent.com/45918704/158749443-2d8269fb-396a-42a9-bcbf-96417f7ddc8c.png">
<img width="1505" alt="image" src="https://user-images.githubusercontent.com/45918704/158749467-d7ba40cc-275f-4b48-ab9b-332bdb218ed1.png">
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/45918704/158749483-b58f1add-f1f9-4a6f-a865-93441166f0b6.png">
this is my parachain xcm log:
![image](https://user-images.githubusercontent.com/45918704/158749611-f0768087-8254-416c-bcee-443a92dd2092.png)

**Comment by 99Kies** [comment]
I failed to configure HRMP.

**Comment by 99Kies** [comment]
I operate according to this blog.  <https://wiki.acala.network/build/development-guide/composable-chains/open-hrmp-channel>

**Comment by zqhxuyuan** [comment]
that's not problem of orml, try increase `requireWeightAtMost`.

**Comment by 99Kies** [comment]
<img width="1490" alt="image" src="https://user-images.githubusercontent.com/45918704/158762296-f7296f13-2a41-49ba-8a5b-3ae1a9301338.png">

![image](https://user-images.githubusercontent.com/45918704/158762277-ba2547ea-f9db-471b-85a4-e7cb824f9e15.png)

**Comment by 99Kies** [comment]
@zqhxuyuan failed with `TooExpansive`.
