### ISSUE TITLE
Events in `tokens` pallet do not completely cover balance changes

### ISSUE THREAD

**Issue by sea212** [open-web3-stack/open-runtime-module-library#726]
Since not every change of token balance is indicated with events, it becomes immensely difficult to correctly track tokens balances in a block indexer.
I suggest to offer a complete set of events that does indicate any changes in token balances like it's done in [the balances pallet](https://github.com/paritytech/substrate/blob/1e3b992499de49b91403dbd1e4a7ba76552e89d1/frame/balances/src/lib.rs#L439-L467).

**Comment by xlc** [comment]
Can you point out what's missing? PR are always welcome.

**Comment by sea212** [comment]
I think the only event that is missing is `Slashed`
```rust
/// Some amount was removed from the account (e.g. for misbehavior).
Slashed { who: T::AccountId, amount: T::Balance },
```

I can create the PR. As I see it now the event belongs into `orml-currency`.
 I am just wondering why are some events like 
```rust
		/// Currency transfer success.
		Transferred {
			currency_id: CurrencyIdOf<T>,
			from: T::AccountId,
			to: T::AccountId,
			amount: BalanceOf<T>,
		},
		/// Update balance success.
		BalanceUpdated {
			currency_id: CurrencyIdOf<T>,
			who: T::AccountId,
			amount: AmountOf<T>,
		},
		/// Deposit success.
		Deposited {
			currency_id: CurrencyIdOf<T>,
			who: T::AccountId,
			amount: BalanceOf<T>,
		},
		/// Withdraw success.
		Withdrawn {
			currency_id: CurrencyIdOf<T>,
			who: T::AccountId,
			amount: BalanceOf<T>,
		},
```
emitted in `orml-currencies`? I think it should just do the calls to the respective trait implementations specified by `Config` types `MultiCurrency` and `NativeCurrency`  and the implementations should be responsible for emitting the events. Otherwise multiple events that state the same will be emitted.

**Comment by xlc** [comment]
The original idea is that events are emitted by the extrinsic pallet (currencies), not the underlying implementation (tokens) so that people can decide what event to emit.

But I does see it could create some inconsistency.

**Comment by shaunxw** [comment]
I agree we should make it that only implementations emit events, and to cover all possible balance changes. In this way ORML users don't have to worry about adding events, and are always free to add custom ones if needed while wrapping these impl.

The current balance related events could be updated as:
1. Add `Slashed` event to `orml-tokens`.
2. In `orml-tokens`, deposit events in traits/pallet impl, instead of in dispatchable calls.
3. Remove events in `orml-currencies`, to get rid of events deposit duplication.

**Comment by syan095** [comment]
orml tokens now emits events whenever balance change occurs.
events are emitted in implementation level. Duplicate deposits are removed.
orml currencie's events have all been removed
