### ISSUE TITLE
The existing Treasury-Pallet seem unable to control the cross-chain fee.

### ISSUE THREAD

**Issue by 99Kies** [open-web3-stack/open-runtime-module-library#738]
I have transferred the commission of cross-chain transfer to Treasury Account, how can I transfer the parallel chain assets in the Treasury account to others?

Are `orml-currencies` willing to accept a method of `froce_transfer(from, to, currency_id, amount)`?

**Comment by xlc** [comment]
You can just handle it in your own pallet.

**Comment by 99Kies** [comment]
@xlc thx.

**Comment by 99Kies** [comment]
@xlc Excuse me, It seems that Acala does not support the control of cross-chain handling fee, may I ask whether this will be supported later?  (because I am learning the code of Acala.😊)

**Comment by xlc** [comment]
It is also possible to spend the funds using utility.dispatch_as to perform currencies.transfer from treasury account.
