### ISSUE TITLE
How does `deposit` work?

### ISSUE THREAD

**Issue by Chralt98** [open-web3-stack/open-runtime-module-library#755]
Could you please explain [this test](https://github.com/open-web3-stack/open-runtime-module-library/blob/e65be8747f4c5245721d281c93746fa17a06f924/currencies/src/tests.rs#L285-L290) to me?

Why does the `DepositFailed` error appear the first time, but not the second time?

**Comment by xlc** [comment]
ED is 2 and therefore deposit 1 failed and deposit 2 succeeded
