### ISSUE TITLE
Create polkadot-v0.9.17 branch

### ISSUE THREAD

**Issue by apopiak** [open-web3-stack/open-runtime-module-library#756]
It would be useful to have a branch pointing to https://github.com/open-web3-stack/open-runtime-module-library/commit/aac79b3b31953381669a2ffa9b3e9bfe48e87f38 similar to 0.9.16 and 0.9.19 (0.9.18 is also missing AFAICT)

**Comment by zqhxuyuan** [comment]
I restored it for v0.9.17: https://github.com/open-web3-stack/open-runtime-module-library/pull/705
