### ISSUE TITLE
[Question] Weight compatibility with substrate pallets

### ISSUE THREAD

**Issue by cowboy-bebug** [open-web3-stack/open-runtime-module-library#790]
Hi team :wave:

I was wondering if the benchmark and weights were run on the same hardware as [the standward hardware](https://wiki.polkadot.network/docs/maintain-guides-how-to-validate-polkadot#standard-hardware) to make the orml-pallets compatible with substrate weights.
Or do you recommend running our own weights?

Thanks!

**Comment by xlc** [comment]
You should always run you own weights. Many calls will invoke hooks and it is runtime specific.

**Comment by cowboy-bebug** [comment]
Thanks @xlc
