### ISSUE TITLE
Add orml-treasury

### ISSUE THREAD

**Issue by gregdhill** [open-web3-stack/open-runtime-module-library#794]
The [treasury pallet](https://github.com/paritytech/substrate/tree/master/frame/treasury) in FRAME does not support multiple currencies, would a multi-currency ORML alternative be of interest? We would also like to simplify the implementation to remove the `SpendPeriod` such that funds approved for spending are transferred instantly.

**Comment by xlc** [comment]
That sounds useful. Could you make a pallet design so we can iterate on it first before the actual implementation?

**Comment by xlc** [comment]
AssetHub is going to have multi asset treasury so no we should just use the pallet over there.
