### ISSUE TITLE
[orml_tokens] How to destroy all balances for one currency id?

### ISSUE THREAD

**Issue by Chralt98** [open-web3-stack/open-runtime-module-library#802]
Is there a way to destroy a whole currency?

[`pallet_assets` uses `drain_prefix`](https://github.com/paritytech/substrate/blob/c1103fd803a974ee4d4098eb631a8839f6cb8618/frame/assets/src/functions.rs#L661-L720) for this, but `orml_tokens` maps from `AccountId` to `CurrencyId`. So there is only the way to iterate over each account? This is very expensive, when there are a lot of different currencies with a lot of accounts with balances. 

You assumed it happens not so often, that a whole currency gets destroyed right?

I don't see any other option then to the iteration over each account to find the specified currency id. Do you have any other idea?

**Comment by xlc** [comment]
Yeah there is no better way.
orml-tokens is optimized to fetch all the tokens for a given user rather than all users for a given token.
What I will suggest is implement an extrinsic in another pallet that takes an array of accounts and remove them. You could make this permissionless or guard it with governance.

**Comment by Chralt98** [comment]
Yeah, I thought about this solution already. Great that you remind me about that. This comes with the cost of storing all accounts in a vector that had something to do (`deposit`, `transfer`) with a specific currency id. I think the best solution is using `pallet_assets` for all the currencies, which need to get destroyed and using `orml_tokens` for all currencies, which need to stay persistently on the chain (no destroying required).
