### ISSUE TITLE
[orml_tokens] Is there a way to query the locks like in `pallet_democracy`?

### ISSUE THREAD

**Issue by Chralt98** [open-web3-stack/open-runtime-module-library#863]
Hey valuable ORML maintainers,

I wonder if there is the possibility to extend my test to check for the locks [like in the democracy pallet](https://github.com/paritytech/substrate/blob/a96cb5725407f8cc5ae7c9efc85a80548d071833/frame/democracy/src/tests/lock_voting.rs#L59)?

Thanks a lot!

**Comment by xlc** [comment]
Not exactly sure what do you mean. Can you clarify? Do you want to add tests? Or asking how to query locks?

**Comment by Chralt98** [comment]
I am just asking how to check for the underlying locks storage item to see which items are behind `orml_currencies` `set_lock` and `extend_lock`. Like in the link above `Balances::locks(i)`. Can I query `Currencies::locks(i)`. I don't think so. Thanks a lot.

**Comment by xlc** [comment]
You can query from tokens. Or you can simply ensure transfer will fail.
