### ISSUE TITLE
DataFeeder: Allow pass the root account.

### ISSUE THREAD

**Issue by lemunozm** [open-web3-stack/open-runtime-module-library#919]
Hi!

I need to insert values into the oracle from another pallet. I do not want to attach that pallet in a tight way, so I would like to use the `DataFeeder` to do that. Nevertheless, I cannot know exactly which account is part of the Oracle pallet's member list from another pallet perspective, and I can not use Root.

It would be great to have some `DataFeeder` method that does not need to use an account. Or at least, allow using an `Option<AccountId>` like the `do_feed_values()` in order to use Root.

If you agree with this modification, I could open a PR with this.

**Comment by ermalkaleci** [comment]
That other pallet account_id can be another member maybe?

**Comment by lemunozm** [comment]
The other pallet uses `DataFeeder` in order to create an initial worst state for benchmarking. Ideally, it could be great if a do not need to modify other pallets to set up an internal benchmark behavior.

**Comment by xlc** [comment]
You could consider use the all zero account?

>  feed_value() only allow feeding one key/value from one account

I don't think this is true? One account can feed multiple keys?

I think we can add a new method to `DataFeeder` trait

`fn feed_values(who: Option<AccountId>, values: &[(Key, Value)] -> DispatchResult;`

and keep the existing one and provide a default implementation to call this new one

In this way we can minimize the breaking change

**Comment by lemunozm** [comment]
> You could consider use the all zero account?

Not sure if I get what you mean here, could you expand? 🙏🏻 

> I don't think this is true? One account can feed multiple keys?

Looking at the signature seems like several calls to this works. Nevertheless, the Oracle implementation does not allow reusing the same account to fetch twice in the same block (getting a `AlreadyFeeded` error), so now I'm stuck fetching one value from one account.

> `fn feed_values(who: Option<AccountId>, values: &[(Key, Value)] -> DispatchResult;`

This is just what I was looking for, it would be awesome to have it! Although I think you can not create a default implementation for it, so it will be a breaking change.

**Comment by lemunozm** [comment]
Another way to not add a new method breaking changes is that the oracle's implementation of `feed_value` skips the `HasDispatched` part.

I mean, the `HasDispatched` check makes sense for external interaction with the oracle, but it seems like a significant restriction from an internal usage using the trait

**Comment by xlc** [comment]
All zero account is basically `AccountId::default()` or `0x0000...0000`

>  Nevertheless, the Oracle implementation does not allow reusing the same account to fetch twice in the same block (getting a AlreadyFeeded error), so now I'm stuck fetching one value from one account.

Right. That could be an issue.

It will be a breaking change for the implementor `DataFeeder`, which usually is orml-oracle and that's fine. For the users, it is compatible. 

Also I don't mind small breaking change as long as there is a good reason. We are all used to deal with all the breaking changes from Substrate anyway...

**Comment by lemunozm** [comment]
> Also I don't mind small breaking change as long as there is a good reason. We are all used to deal with all the breaking changes from Substrate anyway...

That's true 😄 

If you agree, I can open a PR with some draft about what you say above. 

I was thinking that maybe the less invasive change is to check `HasDispatched` only in member accounts, not for the root case. This makes sense because the root has "more" privileges. This, along with passing the accounts as an option in order to choose root by `None`, makes the initialization case works.

**Comment by lemunozm** [comment]
An example of what I mean with my last comment in this PR: https://github.com/open-web3-stack/open-runtime-module-library/pull/920

**Comment by lemunozm** [comment]
I'm curious about the purpose of `HasDispatched` blocking feeds in the same block. Is it because of any security reasons? What capability does this restriction offer to the oracle?

**Comment by xlc** [comment]
Prevent oracle operator to spam the blocks. Valid feed are free and if we allow multiple feeds in a single block, they can fill the blocks for free.
With HasDispatched check, it is only up to 1 tx per operator per block.

**Comment by xlc** [comment]
closed by #920

**Comment by lemunozm** [comment]
Thanks for the answer!

> Valid feed are free and if we allow multiple feeds in a single block, they can fill the blocks for free.

Although seeing the weights, each call to `feed_values()` will cost some fee, isn't it? So filling the block would have a cost.

**Comment by xlc** [comment]
A successful feed is free

https://github.com/open-web3-stack/open-runtime-module-library/blob/0482bf2b02ac8fea1279da0a34c0900fd369c444/oracle/src/lib.rs#L176

**Comment by lemunozm** [comment]
I totally skipt that line 🤦🏻‍♂️. Thanks!
