### ISSUE TITLE
Oracles: unbounded feed values vector

### ISSUE THREAD

**Issue by lemunozm** [open-web3-stack/open-runtime-module-library#924]
The current oracle's extrinsic `feed_values()` allows an unbounded `Vec` as an input parameter. This would allow a member to act badly generating a huge list of values that fill the block computation time for free, because the member is not paying fees under success.

Even if all `OracleKey` possible values are limited, the vector can still contain duplicates that must be iterated, consuming, in the worst case, the entire block available time.

We think the solution to this is as simple as making this `Vec` bounded. If you agree, I can add a PR with this change.

**Comment by xlc** [comment]
I agree. It is usually a good idea to make vec bounded anyway.
