### ISSUE TITLE
Balanced implementation for orml_tokens

### ISSUE THREAD

**Issue by Chralt98** [open-web3-stack/open-runtime-module-library#930]
Hey,

is there any existing implementation for this trait https://paritytech.github.io/substrate/master/frame_support/traits/tokens/fungible/trait.Balanced.html ?

It seems like orml_tokens worked for polkadot version 0.9.40, but now I upgraded to 0.9.42.

```
the trait bound `orml_tokens::Pallet<Runtime>: hidden_include::traits::fungible::Balanced<sp_runtime::AccountId32>` is not satisfied
```

This is where it throws the error:

```rust
impl pallet_asset_tx_payment::OnChargeAssetTransaction<Runtime> for TokensTxCharger {
	type AssetId = BAsset;
	type Balance = Balance;
	type LiquidityInfo = Credit<AccountId, Tokens>;
```

For "Credit<AccountId, Tokens>" and Tokens is orml_tokens.

@xlc otherwise "We are running out of dots..." ;-)

**Comment by xlc** [comment]
Looks like it is indeed missing. PR are welcome!
