### ISSUE TITLE
Vesting to move tokens to account derived from receiver and vesting to allow gov delegation

### ISSUE THREAD

**Issue by dzmitry-lahoda** [open-web3-stack/open-runtime-module-library#947]
it is expected that team vested people are bening and should be able to use future tokens to vote.

so allow to setup proxy for vested account as desired by host runtime config to that account.

which will be usual voting

**Comment by xlc** [comment]
I do not understand the request. Vested token can be used for voting. There is no need to have proxy.

**Comment by dzmitry-lahoda** [comment]
https://github.com/paritytech/substrate/blob/033d4e86cc7eff0066cd376b9375f815761d653c/frame/conviction-voting/src/lib.rs#L625
