### ISSUE TITLE
Cannot read packages due to using workspace dependencies without workspace

### ISSUE THREAD

**Issue by JayPavlina** [open-web3-stack/open-runtime-module-library#980]
This repository is using workspace dependencies, for example:

```
scale-info = { workspace = true }
```

 However, there is no workspace. because the file is called `Cargo.dev.toml` instead of `Cargo.toml`.

When trying to read a package like this:

```
orml-traits = { git = "https://github.com/open-web3-stack/open-runtime-module-library.git" }
```

It will show the error:

```
error: no matching package named `orml-traits` found
location searched: https://github.com/open-web3-stack/open-runtime-module-library.git
```

Forking and renaming `Cargo.dev.toml` to `Cargo.toml` solves the issue.

**Comment by xlc** [comment]
Yeah this is intended. Use `dev-*` tasks from makefile to automatically do the copy for you https://github.com/open-web3-stack/open-runtime-module-library/blob/master/Makefile

**Comment by JayPavlina** [comment]
Removing the workspace dependencies is a better solution and doesn't require workarounds, but I see you've closed the issue.

**Comment by xlc** [comment]
we use workspace dependency for a reason. otherwise upgrading the version of a dependency is complicated
