### ISSUE TITLE
Incorrect version in dev-dependencies for orml version 0.9.0

### ISSUE THREAD

**Issue by clangenb** [open-web3-stack/open-runtime-module-library#989]
Sp-core and pallet balances should be at version 31.0.0 according to the [workspace file](https://github.com/open-web3-stack/open-runtime-module-library/blob/3151b86877ac2e8bfdecd2c8a73374bd5dcd0e5b/Cargo.dev.toml#L60), yet the released crates have version v29.0.0. See expample for pallet-vesting https://crates.io/crates/orml-vesting/0.9.0/dependencies. This leads to duplicate dependencies, which is obviously not ideal.

**Comment by clangenb** [comment]
It is not only not good, it actually breaks the wasm build due to duplicate sp-io crates, which introduce duplicate rust lang items.

**Comment by xlc** [comment]
sorry about that. released 0.9.1 which should have the correct deps
